### ISSUE TITLE
Enoxos

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/lexical-taggers#2]
Enoxos (Enoch) appears in 1 Cor 11.  Enoch is Hebrew name that appears in 1 Cor 11 with a Greek suffix.  @amir-zeldes we discussed this issue in our advisory board meeting today (Hebrew words in Greek vs Hebrew words with specific Greek forms as indicated with a suffix or variant spelling).  What do you want to do with Enoch?  Thanks.

**Comment by amir-zeldes** [comment]
Is this a/the standard way of calling Enoch in Greek? Or is this a derivation creating a distinct, new name?

**Comment by ctschroeder** [comment]
Ok, this is me being an idiot.  Not the name Enoch. Never mind.  I'm deleting this issue.  Sorry.  Blaming it on the pneumonia.
