### ISSUE TITLE
adjust enrich.pl to have two parameters

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/lexical-taggers#3]
consider adjusting enrich.pl to have parameters for the different lexica so we can call the lexicon files without them being int he same directory as enrich.pl

**Comment by amir-zeldes** [comment]
Only had a chance to look at this now - I think this is already the case: the parameter is -l. You can call the script like this:

```
_enrich.pl -l /path/to/lexicon/file.txt INPUT_FILE
```

The lexicon file doesn't have to be in the same folder. Let me know if this doesn't work on Mac, otherwise I would close this issue.

**Comment by ctschroeder** [comment]
Can you put this information in the ReadMe?

**Comment by ctschroeder** [comment]
This parameter would (will? is?) be great for our annotators, because moving enrich.pl around is a hangup for them.

**Comment by amir-zeldes** [comment]
Sure, just added to the readme. It was always inside the script, if you run it with -h or no arguments, or read the file itself.
