### ISSUE TITLE
words to add to lexicon

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/lexical-taggers#4]
ⲉⲓⲇⲟⲥ
ⲙⲱⲛⲟⲛ

**Comment by ElizabethFD** [comment]
ⲭⲏⲣⲁ (widow)
ⲟⲣⲫⲁⲛⲟⲥ

**Comment by ElizabethFD** [comment]
ⲥⲩⲛⲕⲗⲏⲧⲓⲕⲏ
ϩⲩⲡⲟⲙⲓⲛⲉ

**Comment by amir-zeldes** [comment]
Hi all, we can add these but there's no need for issues on github - at the next tokenizer update I will just pull all words from all manually processed corpora and add the missing words to the lexicon. Anything that isn't tagged UNKNOWN will be added, so there's no need to worry about keeping track.

**Comment by ctschroeder** [comment]
Hi. I told everyone to add them to this issue since I update it manually more frequently. (Bc I noticed the same words coming up multiple times when I was proofreading some of the files).  Sorry for the conflicting advice.

**Comment by cluckmarq** [comment]
ⲁⲣⲛⲁ
ⲃⲁⲡⲧⲓⲥⲧⲏⲥ
ⲃⲏⲇⲥⲁⲓⲇⲁⲛ
ⲅⲉⲛⲉⲁ
ⲇⲁⲗⲙⲁⲛⲟⲩⲑⲁ
ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ
ⲏⲇⲏ (also missed that this was an ADV and labeled as N)
ⲕⲁⲗⲱⲥ
ⲕⲉⲥⲁⲣⲓⲁ
ⲅⲉϩⲉⲛⲛⲁ
ϩⲣⲁⲃⲃⲉⲓ
ⲇⲓⲁⲕⲟⲛⲓ
ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ
ⲙⲁⲥⲧⲓⲅⲟⲩ
ⲛⲁⲍⲁⲣⲁⲓⲟⲥ
ⲡⲣⲟⲥ
ⲧⲓⲙⲁⲓⲟⲥ
ⲭⲣⲏⲙⲁ
ϩⲓⲉⲣⲓⲭⲱ
ϩⲣⲁⲃⲃⲟⲩⲛⲉⲓ

**Comment by ctschroeder** [comment]
All of the above have been added
