### ISSUE TITLE
Language tagger in NLP Pipeline

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/lexical-taggers#6]
The language tagger (or the excel importer??) is still misaligning the spans in the NLP pipeline.  Dana Robinson has reported problems.

**Comment by amir-zeldes** [comment]
The plugin seems to work on my iMac (I'm assuming it's the Mac version)... is this the latest Mac version from https://github.com/copticscriptorium/converters (0.9.3)? If so, can you give an example of the misalignment?
